version: '2'
services:
  'nomatrix':
    image: 'rethink/msg-node-nomatrix'
    container_name: 'nomatrix'
    environment:
      - DOMAIN=rethink-dev.tlabscloud.com
      - PORT=8001
      - REGISTRY=http://dev-registry-domain:4567
      - GLOBALREGISTRY=http://130.149.22.133:5002
    networks:
      - rethink
    # external port that will be used by the reverse proxy 
    ports:
      - '8001:8001'

  'dev-registry-domain':
    #image: rethink/registry-domain-server:R0.7.0
    image: rethink/registry-domain-server
    build: /opt/rethink/dev-registry-domain/server
    container_name: 'dev-registry-domain'
    networks:
      - rethink
    environment:
      - STORAGE_TYPE=RAM
      - EXPIRES=3600
    expose:
      - '4568'
      - '4567'
    # external port that will be used by the reverse proxy 
    ports:
      - '4567:4567'

  'catalogue-broker':
    image: rethink/catalogue-broker
    container_name: 'catalogue-broker'
    networks:
      - rethink
    command: [-host, catalogue-broker, -sourcePackageURLHost, catalogue.rethink-dev.tlabscloud.com, -ch, catalogue-broker, -default, protocolstub/MatrixProtoStub, -default, runtime/Runtime]
    expose:
      - '80'
      - '443'
      - '5683'
    # external port that will be used by the reverse proxy 
    ports:
      - '9090:80'


  'catalogue-database':
    image: rethink/catalogue-database
    container_name: 'catalogue-database'
    networks:
      - rethink
    command: [-sourcePackageURLHost, catalogue.rethink-dev.tlabscloud.com, -o, /catalogue-database, -ch, catalogue-database, -h, catalogue-broker/5683]
    depends_on:
      - 'catalogue-broker'
    volumes:
      - '/opt/rethink/testbeds/nodes/DT-node/docker-compose/dev/catalogue_objects:/catalogue-database'

  'toolkit':
    build: '/opt/rethink/testbeds/nodes/DT-node/docker-files/hyperty-toolkit'
    image: 'hyperty-toolkit'
    container_name: 'toolkit'
    environment:
      - DEVELOPMENT=false
      - RUNTIME_URL=hyperty-catalogue://catalogue.rethink-dev.tlabscloud.com/.well-known/runtime/Runtime
      - DOMAIN=rethink-dev.tlabscloud.com
      - HYPERTY_REPO=/hyperty
    volumes:
      - /opt/rethink/dev-hyperty:/hyperty
      - /opt/rethink/dev-callcenter-app:/hyperty-toolkit
    networks:
      - rethink
    # external port that will be used by the reverse proxy 
    ports:
      - '8080:8080'

  'umbrella':
    build: '/opt/rethink/umbrella/docker'
    image: 'rethink/umbrella'
    container_name: 'umbrella'
    volumes:
      - /opt/rethink/umbrella:/opt/rethink/umbrella
    networks:
      - rethink
    # external port that will be used by the reverse proxy 
    ports:
      - '8081:8080'

networks:
  rethink:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

