version: '2'
services:
  'cassandra':
    image: cassandra:latest
    container_name: 'cassandra'
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=192.168.89.95
      - CASSANDRA_ENDPOINT_SNITCH='GossipingPropertyFileSnitch'

    ports:
      - "192.168.89.95:9042:9042"
      - "192.168.89.95:7000:7000"

