version: '2'
services:
  'cassandra':
    image: cassandra:latest
    container_name: 'cassandra'
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
      - CASSANDRA_ENDPOINT_SNITCH='GossipingPropertyFileSnitch'

    ports:
      - "127.0.0.1:9042:9042"
      - "127.0.0.1:7000:7000"

