version: '2'
services:
  'msg-node-vertx':
    image: 'rethinkaltice/dev-msg-node-vertx:latest'
    container_name: 'msg-node-vertx'
    environment:
      - MSG_NODE_CONFIG=env
      - NODE_DOMAIN=hybroker.rethink.ptinovacao.pt
      - NODE_PORT=9090
      - NODE_REGISTRY_URL=http://172.20.0.4:4567
      - NODE_GLOBAL_REGISTRY_URL=http://130.149.22.133:5002
      - NODE_REGISTRY_RETRIES=2
      - NODE_REGISTRY_SSL=false
      - NODE_REGISTRY_OWN_CERTIFICATES=false
    networks:
      rethink:
        ipv4_address: 172.20.0.2
    expose:
      - '443'
      - '9090'

  'domain-registry':
    image: 'rethinkaltice/dev-registry-domain:latest'
    container_name: 'domain-registry'
    networks:
      rethink:
        ipv4_address: 172.20.0.4
    environment:
      - STORAGE_TYPE=RAM
      - EXPIRES=30
      - EXPIRES_MAX=3600
#     - CONTACT_POINTS_IPS=192.168.89.95,192.168.89.96
    expose:
      - '4568'
      - '4567'

  'catalogue-broker':
    image: 'rethink/catalogue-broker:latest'
    container_name: 'catalogue-broker'
    networks:
      rethink:
        ipv4_address: 172.20.0.8
    hostname: 'catalogue.hybroker.rethink.ptinovacao.pt'
    command: [-host, 'catalogue.hybroker.rethink.ptinovacao.pt', -default, protocolstub/VertxProtoStub, -default, protocolstub/VertxProtoStubNode]

    expose:
      - '443'
      - '5683'

  'catalogue-database-ptinovacao':
    build: "./catalogue-database"
    container_name: 'catalogue-database-ptinovacao'
    network_mode: "service:catalogue-broker"
    command: [-host, catalogue.hybroker.rethink.ptinovacao.pt]
    depends_on:
      - 'catalogue-broker'

#  'global-registry'
#    build: 'rethink/global-registry'
#    container_name: 'global-registry'
#    environment:
#      - KEY=VALUE
#    networks:
#      rethink:
#        ipv4_address: 172.18.0.16
#    expose:
#      - '443'

#  'hyperty-toolkit':
#    image: vitormtsilva/dev-hyperty-toolkit:develop
#    container_name: 'hyperty-toolkit'
#    environment:
#      - DEVELOPMENT=false
#      - RUNTIME_URL=hyperty-catalogue://catalogue.hybroker.rethink.ptinovacao.pt/.well-known/runtime/Runtime
#      - DOMAIN=hybroker.rethink.ptinovacao.pt
#      - HYPERTY_REPO=/tmp/dev-hyperty
#      - INDEX_URL=https://hybroker.rethink.ptinovacao.pt/.well-known/runtime/index.html
#      - SANDBOX_URL=https://hybroker.rethink.ptinovacao.pt/.well-known/runtime/sandbox.html
#      - HYPERTY_TEMPLATES_PATH=examples
#      - HYPERTY_SOURCECODE_PATH=src
#      - HYPERTY_INCLUDES=connector, group-chat-manager, user-availability, hello-world, node-hyperty, node-hyperty-observer
#    entrypoint: 'npm run start:prod'
##    entrypoint: 'npm run start:browser'
#    volumes:
#      - devHypertyVolume:/tmp/dev-hyperty
#    networks:
#      rethink:
#        ipv4_address: 172.20.0.32
#    expose:
#      - '443'
#    depends_on:
#      - 'hyperty-database'

#  'hyperty-database':
#    image: 'rethink/dev-hyperty:develop'
#    container_name: 'hyperty-database'
#    volumes:
#      - devHypertyVolume:/opt/reTHINK/dev-hyperty/

#  'rethink-app':
#    build: '../../../../dev-smart-contextual-assistance-app/'
#    container_name: 'rethink-app'
#
#    networks:
#      rethink:
#        ipv4_address: 172.20.0.16
#    expose:
#      - '443'
#      - '8080'


  'hyperty-toolkit':
          # image: vitormtsilva/dev-hyperty-toolkit:develop
    build: '../dev-hyperty-toolkit'
    container_name: 'hyperty-toolkit'
    environment:
      - DEVELOPMENT=false
      - RUNTIME_URL=hyperty-catalogue://catalogue.hybroker.rethink.ptinovacao.pt/.well-known/runtime/Runtime
      - DOMAIN=hybroker.rethink.ptinovacao.pt
      - HYPERTY_REPO=/home/dev-hyperty
      - PROTOSTUB_REPO=/home/dev-protostubs
      - INDEX_URL=https://hybroker.rethink.ptinovacao.pt/.well-known/runtime/index.html
      - SANDBOX_URL=https://hybroker.rethink.ptinovacao.pt/.well-known/runtime/sandbox.html
      - HYPERTY_INCLUDES=connector, group-chat-manager, user-availability, hello-world, node-hyperty, node-hyperty-observer, location, dtwebrtc, simple-chat, learning, device-manager
    volumes:
      - ../dev-hyperty:/home/dev-hyperty
      - ../dev-protostubs:/home/dev-protostubs
    networks:
      rethink:
        ipv4_address: 172.20.0.32
    expose:
      - '443'
    entrypoint: 'npm run start:browser'


  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    networks:
      rethink:
        ipv4_address: 172.20.0.64
    expose:
      - '27017'


  'dev-java-hyperty':
    image: 'rethinkaltice/dev-java-hyperty:fromdevelop'
    container_name: "dev-java-hyperty"
    environment:
      - MONGOHOSTS=172.20.0.64
      - MONGOPORTS=27017
      - MONGO_CLUSTER=NO

    networks:
      rethink:
        ipv4_address: 172.20.0.128
    expose:
      - '443'
      - '9091'

  mongodbfirst:
    image: mongo:latest
    container_name: "mongodbfirst"
    volumes:
      - ./m1:/data
    ports:
      - "192.168.89.95:27017:27017"
      - "127.0.0.1:27017:27017"
    command: mongod --smallfiles --replSet testeMongo
    networks:
      rethink:
        ipv4_address: 172.20.0.65

  portainer_container:
    image: portainer/portainer
    container_name: "portainer_container"
    ports:
      - "192.168.89.95:9000:9000"
      - "127.0.0.1:9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      rethink:
        ipv4_address: 172.20.0.5


volumes:
    devHypertyVolume:


networks:
  rethink:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
