version: '2'
services:
  'msg-node-vertx':
    image: 'rethink/msg-node-vertx:master'
    container_name: 'msg-node-vertx'
    environment:
      - MSG_NODE_CONFIG=env
      - NODE_DOMAIN=hybroker.rethink.ptinovacao.pt
      - NODE_PORT=9090
      - NODE_REGISTRY_URL=http://172.18.0.4:4567
      - NODE_GLOBAL_REGISTRY_URL=http://130.149.22.133:5002
      - NODE_REGISTRY_RETRIES=2
      - NODE_REGISTRY_SSL=false
      - NODE_REGISTRY_OWN_CERTIFICATES=false
    networks:
      rethink:
        ipv4_address: 172.18.0.2
    expose:
      - '443'
      - '9090'

  'domain-registry':
    image: 'rethink/registry-domain-server:master'
    container_name: 'domain-registry'
    networks:
      rethink:
        ipv4_address: 172.18.0.4
    environment:
      - STORAGE_TYPE=RAM
      - EXPIRES=3600
    expose:
      - '4568'
      - '4567'

  'catalogue-broker':
    image: 'rethink/catalogue-broker:master'
    container_name: 'catalogue-broker'
    networks:
      rethink:
        ipv4_address: 172.18.0.8
    hostname: 'catalogue.hybroker.rethink.ptinovacao.pt'
    command: [-host, 'catalogue.hybroker.rethink.ptinovacao.pt', -default, protocolstub/VertxProtoStub, -default, protocolstub/VertxProtoStubNode]

    expose:
      - '443'
      - '5683'

  'catalogue-database-ptinovacao':
    build: "./catalogue-database"
    container_name: 'catalogue-database-ptinovacao'
    network_mode: "service:catalogue-broker"
    command: [-host, catalogue.hybroker.rethink.ptinovacao.pt]
    depends_on:
      - 'catalogue-broker'

#  'global-registry'
#    build: 'rethink/global-registry'
#    container_name: 'global-registry'
#    environment:
#      - KEY=VALUE
#    networks:
#      rethink:
#        ipv4_address: 172.18.0.16
#    expose:
#      - '443'

  'hyperty-toolkit':
    image: vitormtsilva/dev-hyperty-toolkit:develop
    container_name: 'hyperty-toolkit'
    environment:
      - DEVELOPMENT=false
      - RUNTIME_URL=hyperty-catalogue://catalogue.hybroker.rethink.ptinovacao.pt/.well-known/runtime/Runtime
      - DOMAIN=hybroker.rethink.ptinovacao.pt
      - HYPERTY_REPO=/tmp/dev-hyperty
    volumes:
      - devHypertyVolume:/tmp/dev-hyperty
    networks:
      rethink:
        ipv4_address: 172.18.0.32
    expose:
      - '443'
    depends_on:
      - 'hyperty-database'

  'hyperty-database':
    image: 'rethink/dev-hyperty:develop'
    container_name: 'hyperty-database'
    volumes:
      - devHypertyVolume:/opt/reTHINK/dev-hyperty/

volumes:
    devHypertyVolume:


networks:
  rethink:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
