# Baseline docker file for all docker images that are
# supported on rethink testbed installations.
#
# Note: it is mandatroy, that ALL docker files for images
# to be deployed on the rethink tesbed derive from this
# image.

FROM ubuntu:14.04
MAINTAINER marc.emmelmann@fokus.fraunhofer.de


